###############
#             #
# Main config #
#             #
###############

kitSelectorItem:
  name: '&bKit Selector'
  lore:
    - '&bUse me to select your kit!'
  mat: 'COMPASS'
  slot: 1

kitSelectorGUI:
  name: '&bSelect your kit!'
  slots: 27

# Crate drop items
# Format:
#   - 'ITEM_NAME:COUNT:DATA:ENCHANTMENT~LEVEL:ENCHANTMENT~LEVEL:ENCHANTMENT~LEVEL.....'
crateDropItems:
  - 'GOLDEN_APPLE:5:0'
  - 'DIAMOND_CHESTPLATE:1:0'
  - 'APPLE:2:0'
  - 'ENDER_PEARL:1:0'
  - 'DIAMOND_SWORD:1:0:DAMAGE_ALL~1'
