name: DesertedPvP
main: codes.matthewp.desertedpvp.DesertedPvP
version: 0.0.1

commands:
  setspawn:
    description: Set the spawn
  spawn:
    description: Go to spawn
  addks:
    description: Add to a players kill streak
  resetks:
    description: Reset a players kill streak
  balance:
    description: Get your current balance
